### ISSUE TITLE
Using TMPDIR instead of current users home.

### ISSUE THREAD

**Issue by qzaidi** [google/gops#31]
It may be a better idea to use TMPDIR instead of current user's home directory for writing gops port files. The homedir may not be writable, while TMPDIR is. It also allows us to run gops binary with a different user than the app embedding the gops agent.

**Comment by rakyll** [comment]
TMPDIR might be deleted, PID files shouldn't get lost. In the case of long-running processes, you don't want to end up seeing you cannot access to a problematic server because the PID file is gone.

We just merged a PR that allows you to use gops against an address, does that work for you better?
https://github.com/google/gops/commit/288e543feeb9fe04d4672f373e0b0a04efca840a

Maybe we should just silently ignore when we cannot write a PID file and expect user to target the address when they are using the command line tool.

**Comment by SvenDowideit** [comment]
I'm having a quick play adding gops to RancherOS, and so some of the go processes are in namespaced filesystems. I think at the moment, `/run` is common to _most_ of the containers - so I'm wondering if we could add an agent Option `GopsDir`, and either softlink that into the user's `.config`, use a `GOPSDIR` env var, or something else way more clever :)

**Comment by zuoRambo** [comment]
https://github.com/google/gops/issues/60

**Comment by xaurx** [comment]
it is still an issue if one tries to run inside k8s container with read only root file system.
if nobody objects I would simply ignore ```read-only file system``` and ```permission denied``` errors on mkdir/write of config. We have remote mode anyway.

opinion?

**Comment by inliquid** [comment]
@xaurx just got the same issue, k8s environment and read-only filesystem. Maybe give an option to not write to `portfile` at all?
